// Code generated by zenrpc v2.3.2; DO NOT EDIT.

package dashboard

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"

	"time"
)

var RPC = struct {
	AttackService  struct{ Enable, Disable, Status, IsEnabled, EnableAuto, DisableAuto, Source string }
	BlockService   struct{ Add, Remove, List string }
	ConfigService  struct{ Get string }
	EventsService  struct{ Recent string }
	FilterService  struct{ Add, Remove, List string }
	MetricsService struct{ History, RPS, Tops, CaptchaRate, Latencies string }
	StatusService  struct{ Get, Rules string }
}{
	AttackService: struct{ Enable, Disable, Status, IsEnabled, EnableAuto, DisableAuto, Source string }{
		Enable:      "enable",
		Disable:     "disable",
		Status:      "status",
		IsEnabled:   "isenabled",
		EnableAuto:  "enableauto",
		DisableAuto: "disableauto",
		Source:      "source",
	},
	BlockService: struct{ Add, Remove, List string }{
		Add:    "add",
		Remove: "remove",
		List:   "list",
	},
	ConfigService: struct{ Get string }{
		Get: "get",
	},
	EventsService: struct{ Recent string }{
		Recent: "recent",
	},
	FilterService: struct{ Add, Remove, List string }{
		Add:    "add",
		Remove: "remove",
		List:   "list",
	},
	MetricsService: struct{ History, RPS, Tops, CaptchaRate, Latencies string }{
		History:     "history",
		RPS:         "rps",
		Tops:        "tops",
		CaptchaRate: "captcharate",
		Latencies:   "latencies",
	},
	StatusService: struct{ Get, Rules string }{
		Get:   "get",
		Rules: "rules",
	},
}

func (AttackService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Enable": {
				Description: `Enable activates Under Attack Mode.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "duration",
						Optional:    true,
						Description: `Duration (e.g. "5m", "1h"). Empty = until manual disable`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `AttackStatus`,
					Type:        smd.Object,
					TypeName:    "AttackStatus",
					Properties: smd.PropertyList{
						{
							Name: "enabled",
							Type: smd.Boolean,
						},
						{
							Name:        "source",
							Description: `"manual" | "auto"`,
							Type:        smd.String,
						},
						{
							Name:        "triggers",
							Description: `trigger names when source=auto`,
							Type:        smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "since",
							Type: smd.String,
						},
						{
							Name: "expiresAt",
							Type: smd.String,
						},
					},
				},
			},
			"Disable": {
				Description: `Disable deactivates Under Attack Mode.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `AttackStatus`,
					Type:        smd.Object,
					TypeName:    "AttackStatus",
					Properties: smd.PropertyList{
						{
							Name: "enabled",
							Type: smd.Boolean,
						},
						{
							Name:        "source",
							Description: `"manual" | "auto"`,
							Type:        smd.String,
						},
						{
							Name:        "triggers",
							Description: `trigger names when source=auto`,
							Type:        smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "since",
							Type: smd.String,
						},
						{
							Name: "expiresAt",
							Type: smd.String,
						},
					},
				},
			},
			"Status": {
				Description: `Status returns the current Under Attack Mode state.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `AttackStatus`,
					Type:        smd.Object,
					TypeName:    "AttackStatus",
					Properties: smd.PropertyList{
						{
							Name: "enabled",
							Type: smd.Boolean,
						},
						{
							Name:        "source",
							Description: `"manual" | "auto"`,
							Type:        smd.String,
						},
						{
							Name:        "triggers",
							Description: `trigger names when source=auto`,
							Type:        smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "since",
							Type: smd.String,
						},
						{
							Name: "expiresAt",
							Type: smd.String,
						},
					},
				},
			},
			"IsEnabled": {
				Description: `IsEnabled returns whether Under Attack Mode is active (for middleware).`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type: smd.Boolean,
				},
			},
			"EnableAuto": {
				Description: `EnableAuto activates Under Attack Mode from adaptive engine.`,
				Parameters: []smd.JSONSchema{
					{
						Name:       "duration",
						Type:       smd.Object,
						TypeName:   "TimeDuration",
						Properties: smd.PropertyList{},
					},
					{
						Name:     "triggers",
						Type:     smd.Array,
						TypeName: "[]",
						Items: map[string]string{
							"type": smd.String,
						},
					},
				},
			},
			"DisableAuto": {
				Description: `DisableAuto deactivates Under Attack Mode (for adaptive engine, no context needed).`,
				Parameters:  []smd.JSONSchema{},
			},
			"Source": {
				Description: `Source returns the source of the current attack mode ("manual", "auto", or "").`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type: smd.String,
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s AttackService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.AttackService.Enable:
		var args = struct {
			Duration *string `json:"duration"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"duration"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		//zenrpc:duration="" Duration (e.g. "5m", "1h"). Empty = until manual disable
		if args.Duration == nil {
			var v string = ""
			args.Duration = &v
		}

		resp.Set(s.Enable(ctx, *args.Duration))

	case RPC.AttackService.Disable:
		resp.Set(s.Disable(ctx))

	case RPC.AttackService.Status:
		resp.Set(s.Status(ctx))

	case RPC.AttackService.IsEnabled:
		resp.Set(s.IsEnabled())

	case RPC.AttackService.EnableAuto:
		var args = struct {
			Duration time.Duration `json:"duration"`
			Triggers []string      `json:"triggers"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"duration", "triggers"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		s.EnableAuto(args.Duration, args.Triggers)

	case RPC.AttackService.DisableAuto:
		s.DisableAuto()

	case RPC.AttackService.Source:
		resp.Set(s.Source())

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (BlockService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Add": {
				Description: `Add adds a block rule.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "blockType",
						Description: `Block type: "ip", "cidr", "country"`,
						Type:        smd.String,
					},
					{
						Name:        "value",
						Description: `Value to block (IP address, CIDR, country code)`,
						Type:        smd.String,
					},
					{
						Name:        "reason",
						Description: `Reason for blocking`,
						Type:        smd.String,
					},
					{
						Name:        "duration",
						Optional:    true,
						Description: `Optional duration (e.g. "1h", "30m"). Empty = permanent`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					400: "Bad Request",
				},
			},
			"Remove": {
				Description: `Remove removes a block rule.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "blockType",
						Description: `Block type: "ip", "cidr", "country"`,
						Type:        smd.String,
					},
					{
						Name:        "value",
						Description: `Value to unblock`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					400: "Bad Request",
				},
			},
			"List": {
				Description: `List returns blocked items by type.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "blockType",
						Description: `Block type: "ip", "cidr", "country"`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]BlockEntry`,
					Type:        smd.Array,
					TypeName:    "[]BlockEntry",
					Items: map[string]string{
						"$ref": "#/definitions/BlockEntry",
					},
					Definitions: map[string]smd.Definition{
						"BlockEntry": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "type",
									Type: smd.String,
								},
								{
									Name: "value",
									Type: smd.String,
								},
								{
									Name: "reason",
									Type: smd.String,
								},
								{
									Name: "addedAt",
									Type: smd.String,
								},
								{
									Name: "expiresAt",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					400: "Bad Request",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s BlockService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.BlockService.Add:
		var args = struct {
			BlockType string  `json:"blockType"`
			Value     string  `json:"value"`
			Reason    string  `json:"reason"`
			Duration  *string `json:"duration"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"blockType", "value", "reason", "duration"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		//zenrpc:duration="" Optional duration (e.g. "1h", "30m"). Empty = permanent
		if args.Duration == nil {
			var v string = ""
			args.Duration = &v
		}

		resp.Set(s.Add(ctx, args.BlockType, args.Value, args.Reason, *args.Duration))

	case RPC.BlockService.Remove:
		var args = struct {
			BlockType string `json:"blockType"`
			Value     string `json:"value"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"blockType", "value"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Remove(ctx, args.BlockType, args.Value))

	case RPC.BlockService.List:
		var args = struct {
			BlockType string `json:"blockType"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"blockType"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.List(ctx, args.BlockType))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (ConfigService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Get": {
				Description: `Get returns the full configuration (secrets masked).`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `ConfigResponse`,
					Type:        smd.Object,
					TypeName:    "ConfigResponse",
					Properties: smd.PropertyList{
						{
							Name: "proxy",
							Ref:  "#/definitions/ProxySection",
							Type: smd.Object,
						},
						{
							Name: "management",
							Ref:  "#/definitions/ManagementSection",
							Type: smd.Object,
						},
						{
							Name: "jsonrpc",
							Ref:  "#/definitions/JSONRPCSection",
							Type: smd.Object,
						},
						{
							Name: "waf",
							Ref:  "#/definitions/WAFSection",
							Type: smd.Object,
						},
						{
							Name: "rateLimit",
							Ref:  "#/definitions/RateLimitSection",
							Type: smd.Object,
						},
						{
							Name: "ip",
							Ref:  "#/definitions/IPSection",
							Type: smd.Object,
						},
						{
							Name: "trafficFilter",
							Ref:  "#/definitions/TrafficFilterSection",
							Type: smd.Object,
						},
						{
							Name: "signing",
							Ref:  "#/definitions/SigningSection",
							Type: smd.Object,
						},
						{
							Name: "decision",
							Ref:  "#/definitions/DecisionSection",
							Type: smd.Object,
						},
						{
							Name: "captcha",
							Ref:  "#/definitions/CaptchaSection",
							Type: smd.Object,
						},
						{
							Name: "alerting",
							Ref:  "#/definitions/AlertingSection",
							Type: smd.Object,
						},
						{
							Name: "adaptive",
							Ref:  "#/definitions/AdaptiveSection",
							Type: smd.Object,
						},
						{
							Name: "storage",
							Ref:  "#/definitions/StorageSection",
							Type: smd.Object,
						},
					},
					Definitions: map[string]smd.Definition{
						"ProxySection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "listen",
									Type: smd.String,
								},
								{
									Name: "targets",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "serviceName",
									Type: smd.String,
								},
								{
									Name: "platforms",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "readTimeout",
									Type: smd.String,
								},
								{
									Name: "writeTimeout",
									Type: smd.String,
								},
								{
									Name: "idleTimeout",
									Type: smd.String,
								},
								{
									Name: "maxRequestBody",
									Type: smd.String,
								},
								{
									Name: "realIpHeaders",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "trustedProxies",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "cbEnabled",
									Type: smd.Boolean,
								},
								{
									Name: "cbThreshold",
									Type: smd.Integer,
								},
								{
									Name: "cbTimeout",
									Type: smd.String,
								},
								{
									Name: "staticPaths",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "staticExts",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name:        "targetDiscoveryEnabled",
									Description: `target discovery (DNS SRV)`,
									Type:        smd.Boolean,
								},
								{
									Name: "targetDiscoveryHost",
									Type: smd.String,
								},
								{
									Name: "targetDiscoveryScheme",
									Type: smd.String,
								},
								{
									Name: "targetDiscoveryDns",
									Type: smd.String,
								},
								{
									Name: "targetDiscoveryRefresh",
									Type: smd.String,
								},
								{
									Name: "targetDiscoveryTimeout",
									Type: smd.String,
								},
							},
						},
						"ManagementSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "listen",
									Type: smd.String,
								},
							},
						},
						"JSONRPCSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "endpoints",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/JSONRPCEndpointInfo",
									},
								},
							},
						},
						"JSONRPCEndpointInfo": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "path",
									Type: smd.String,
								},
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "schemaUrl",
									Type: smd.String,
								},
								{
									Name: "schemaRefresh",
									Type: smd.String,
								},
								{
									Name: "methodWhitelist",
									Type: smd.Boolean,
								},
								{
									Name: "maxBatchSize",
									Type: smd.Integer,
								},
							},
						},
						"WAFSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "enabled",
									Type: smd.Boolean,
								},
								{
									Name: "mode",
									Type: smd.String,
								},
								{
									Name: "paranoiaLevel",
									Type: smd.Integer,
								},
							},
						},
						"RateLimitSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "enabled",
									Type: smd.Boolean,
								},
								{
									Name: "perIp",
									Type: smd.String,
								},
								{
									Name: "action",
									Type: smd.String,
								},
								{
									Name: "maxCounters",
									Type: smd.Integer,
								},
								{
									Name: "rules",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/RuleInfo",
									},
								},
							},
						},
						"RuleInfo": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "endpoint",
									Type: smd.String,
								},
								{
									Name: "match",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "limit",
									Type: smd.String,
								},
								{
									Name: "action",
									Type: smd.String,
								},
							},
						},
						"IPSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "geoDatabase",
									Type: smd.Boolean,
								},
								{
									Name: "asnDatabase",
									Type: smd.Boolean,
								},
								{
									Name: "whitelistCidrs",
									Type: smd.Integer,
								},
								{
									Name: "blacklistCidrs",
									Type: smd.Integer,
								},
								{
									Name: "verifyBots",
									Type: smd.Boolean,
								},
								{
									Name: "botDomains",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "fakeBotScore",
									Type: smd.Float,
								},
								{
									Name: "blockCountries",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "captchaCountries",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "logCountries",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "reputation",
									Ref:  "#/definitions/ReputationInfo",
									Type: smd.Object,
								},
							},
						},
						"ReputationInfo": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "enabled",
									Type: smd.Boolean,
								},
								{
									Name: "updateInterval",
									Type: smd.String,
								},
								{
									Name: "scoreAdjustment",
									Type: smd.Float,
								},
								{
									Name: "firehol",
									Type: smd.Boolean,
								},
								{
									Name: "fireholLevel",
									Type: smd.Integer,
								},
								{
									Name: "tor",
									Type: smd.Boolean,
								},
								{
									Name: "torAction",
									Type: smd.String,
								},
								{
									Name: "datacenter",
									Type: smd.Boolean,
								},
								{
									Name: "dcScore",
									Type: smd.Float,
								},
								{
									Name: "feedCount",
									Type: smd.Integer,
								},
							},
						},
						"TrafficFilterSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "enabled",
									Type: smd.Boolean,
								},
								{
									Name: "ruleCount",
									Type: smd.Integer,
								},
							},
						},
						"SigningSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "enabled",
									Type: smd.Boolean,
								},
								{
									Name: "mode",
									Type: smd.String,
								},
								{
									Name: "ttl",
									Type: smd.String,
								},
								{
									Name: "nonceCache",
									Type: smd.Integer,
								},
								{
									Name: "web",
									Type: smd.Boolean,
								},
								{
									Name: "android",
									Type: smd.Boolean,
								},
								{
									Name: "ios",
									Type: smd.Boolean,
								},
								{
									Name: "methods",
									Type: smd.Integer,
								},
							},
						},
						"DecisionSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "captchaThreshold",
									Type: smd.Float,
								},
								{
									Name: "blockThreshold",
									Type: smd.Float,
								},
								{
									Name: "captchaStatusCode",
									Type: smd.Integer,
								},
								{
									Name: "blockStatusCode",
									Type: smd.Integer,
								},
								{
									Name: "captchaToBlock",
									Type: smd.Integer,
								},
								{
									Name: "captchaToBlockWindow",
									Type: smd.String,
								},
								{
									Name: "softBlockDuration",
									Type: smd.String,
								},
								{
									Name: "captchaFallback",
									Type: smd.String,
								},
								{
									Name: "platforms",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/PlatformCaptchaInfo",
									},
								},
							},
						},
						"PlatformCaptchaInfo": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "platform",
									Type: smd.String,
								},
								{
									Name: "captcha",
									Type: smd.Boolean,
								},
								{
									Name: "minVersion",
									Type: smd.String,
								},
								{
									Name: "fallback",
									Type: smd.String,
								},
							},
						},
						"CaptchaSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "provider",
									Type: smd.String,
								},
								{
									Name: "hasKeys",
									Type: smd.Boolean,
								},
								{
									Name: "cookieName",
									Type: smd.String,
								},
								{
									Name: "cookieTtl",
									Type: smd.String,
								},
								{
									Name: "ipCacheTtl",
									Type: smd.String,
								},
							},
						},
						"AlertingSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "enabled",
									Type: smd.Boolean,
								},
								{
									Name: "webhookCount",
									Type: smd.Integer,
								},
							},
						},
						"AdaptiveSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "enabled",
									Type: smd.Boolean,
								},
								{
									Name: "mode",
									Type: smd.String,
								},
								{
									Name: "evalInterval",
									Type: smd.String,
								},
								{
									Name: "warmupDuration",
									Type: smd.String,
								},
								{
									Name: "rpsMultiplier",
									Type: smd.Float,
								},
								{
									Name: "rpsRecovery",
									Type: smd.Float,
								},
								{
									Name: "minRps",
									Type: smd.Float,
								},
								{
									Name: "errorRate",
									Type: smd.Float,
								},
								{
									Name: "latencyMs",
									Type: smd.Float,
								},
								{
									Name: "blockedRate",
									Type: smd.Float,
								},
								{
									Name: "window",
									Type: smd.String,
								},
								{
									Name: "cooldown",
									Type: smd.String,
								},
								{
									Name: "duration",
									Type: smd.String,
								},
							},
						},
						"StorageSection": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "backend",
									Type: smd.String,
								},
								{
									Name: "hosts",
									Type: smd.Integer,
								},
								{
									Name: "namespace",
									Type: smd.String,
								},
								{
									Name: "keyPrefix",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s ConfigService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}

	switch method {
	case RPC.ConfigService.Get:
		resp.Set(s.Get(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (EventsService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Recent": {
				Description: `Recent returns the last N security events.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "limit",
						Optional:    true,
						Description: `Maximum number of events to return`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]EventEntry`,
					Type:        smd.Array,
					TypeName:    "[]EventEntry",
					Items: map[string]string{
						"$ref": "#/definitions/EventEntry",
					},
					Definitions: map[string]smd.Definition{
						"EventEntry": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "time",
									Type: smd.String,
								},
								{
									Name: "type",
									Type: smd.String,
								},
								{
									Name: "clientIp",
									Type: smd.String,
								},
								{
									Name: "path",
									Type: smd.String,
								},
								{
									Name: "detail",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s EventsService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.EventsService.Recent:
		var args = struct {
			Limit *int `json:"limit"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"limit"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		//zenrpc:limit=50 Maximum number of events to return
		if args.Limit == nil {
			var v int = 50
			args.Limit = &v
		}

		resp.Set(s.Recent(ctx, *args.Limit))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (FilterService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Add": {
				Description: `Add adds a dynamic traffic filter rule. //zenrpc`,
				Parameters: []smd.JSONSchema{
					{
						Name:     "rule",
						Type:     smd.Object,
						TypeName: "FilterRuleParams",
						Properties: smd.PropertyList{
							{
								Name: "name",
								Type: smd.String,
							},
							{
								Name:        "action",
								Description: `"block" | "captcha" | "log"`,
								Type:        smd.String,
							},
							{
								Name: "ip",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "uaExact",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "uaPrefix",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "uaExclude",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "country",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "platform",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "version",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "host",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "path",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "method",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "uaContains",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "asn",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.Integer,
								},
							},
							{
								Name: "rpcMethod",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "referer",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type: smd.String,
				},
			},
			"Remove": {
				Description: `Remove removes a dynamic traffic filter rule by name. //zenrpc`,
				Parameters: []smd.JSONSchema{
					{
						Name: "name",
						Type: smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Type: smd.String,
				},
			},
			"List": {
				Description: `List returns all traffic filter rules (static + dynamic). //zenrpc`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]FilterRuleInfo",
					Items: map[string]string{
						"$ref": "#/definitions/FilterRuleInfo",
					},
					Definitions: map[string]smd.Definition{
						"FilterRuleInfo": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name:        "action",
									Description: `"block" | "captcha" | "log"`,
									Type:        smd.String,
								},
								{
									Name: "ip",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "uaExact",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "uaPrefix",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "uaExclude",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "country",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "platform",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "version",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "host",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "path",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "method",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "uaContains",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "asn",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.Integer,
									},
								},
								{
									Name: "rpcMethod",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "referer",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name:        "source",
									Description: `"config" | "api"`,
									Type:        smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s FilterService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.FilterService.Add:
		var args = struct {
			Rule FilterRuleParams `json:"rule"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"rule"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Add(args.Rule))

	case RPC.FilterService.Remove:
		var args = struct {
			Name string `json:"name"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Remove(args.Name))

	case RPC.FilterService.List:
		resp.Set(s.List())

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (MetricsService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"History": {
				Description: `History returns time series data points for the last N minutes.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "minutes",
						Optional:    true,
						Description: `Number of minutes of history (max 30)`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]event.Point`,
					Type:        smd.Array,
					TypeName:    "[]EventPoint",
					Items: map[string]string{
						"$ref": "#/definitions/event.Point",
					},
					Definitions: map[string]smd.Definition{
						"event.Point": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:        "time",
									Description: `unix timestamp`,
									Type:        smd.Integer,
								},
								{
									Name:        "incoming",
									Description: `total requests entering pipeline`,
									Type:        smd.Integer,
								},
								{
									Name:        "requests",
									Description: `requests reaching backend`,
									Type:        smd.Integer,
								},
								{
									Name: "blocked",
									Type: smd.Integer,
								},
								{
									Name: "filtered",
									Type: smd.Integer,
								},
								{
									Name: "rateLimited",
									Type: smd.Integer,
								},
								{
									Name: "captcha",
									Type: smd.Integer,
								},
								{
									Name: "captchaPass",
									Type: smd.Integer,
								},
								{
									Name: "wafMatches",
									Type: smd.Integer,
								},
								{
									Name: "signInvalid",
									Type: smd.Integer,
								},
								{
									Name: "errors5xx",
									Type: smd.Integer,
								},
								{
									Name:        "latencyUs",
									Description: `sum of response latencies (microseconds)`,
									Type:        smd.Integer,
								},
								{
									Name:        "latencyCount",
									Description: `number of responses`,
									Type:        smd.Integer,
								},
								{
									Name:        "latencyMaxUs",
									Description: `max response latency (microseconds)`,
									Type:        smd.Integer,
								},
								{
									Name:        "bytesSent",
									Description: `total response bytes`,
									Type:        smd.Integer,
								},
							},
						},
					},
				},
			},
			"RPS": {
				Description: `RPS returns the current requests per second.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `float64`,
					Type:        smd.Float,
				},
			},
			"Tops": {
				Description: `Tops returns top-N IPs, paths, and countries for the current window.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "n",
						Optional:    true,
						Description: `Number of top entries`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `TopsResult`,
					Type:        smd.Object,
					TypeName:    "TopsResult",
					Properties: smd.PropertyList{
						{
							Name: "ips",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/IPTopEntry",
							},
						},
						{
							Name: "blockedIps",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/IPTopEntry",
							},
						},
						{
							Name: "paths",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "countries",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "platforms",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "wafRules",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "bots",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "fakeBots",
							Type: smd.Integer,
						},
						{
							Name: "userAgents",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "referers",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "rpcMethods",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "asns",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "signResults",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
						{
							Name: "decisions",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.TopEntry",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"IPTopEntry": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "ip",
									Type: smd.String,
								},
								{
									Name: "total",
									Type: smd.Integer,
								},
								{
									Name: "blocked",
									Type: smd.Integer,
								},
								{
									Name: "country",
									Type: smd.String,
								},
								{
									Name: "asnOrg",
									Type: smd.String,
								},
							},
						},
						"event.TopEntry": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "key",
									Type: smd.String,
								},
								{
									Name: "total",
									Type: smd.Integer,
								},
								{
									Name: "blocked",
									Type: smd.Integer,
								},
							},
						},
					},
				},
			},
			"CaptchaRate": {
				Description: `CaptchaRate returns captcha solve rate for the last N minutes.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "minutes",
						Optional:    true,
						Description: `Number of minutes of history (max 30)`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `CaptchaRateResult`,
					Type:        smd.Object,
					TypeName:    "CaptchaRateResult",
					Properties: smd.PropertyList{
						{
							Name: "captcha",
							Type: smd.Integer,
						},
						{
							Name: "captchaPass",
							Type: smd.Integer,
						},
						{
							Name:        "solveRate",
							Description: `CaptchaPass / Captcha * 100`,
							Type:        smd.Float,
						},
					},
				},
			},
			"Latencies": {
				Description: `Latencies returns per-target and per-method latency statistics.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `LatenciesResult`,
					Type:        smd.Object,
					TypeName:    "LatenciesResult",
					Properties: smd.PropertyList{
						{
							Name: "targets",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.LatencyEntry",
							},
						},
						{
							Name: "methods",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.LatencyEntry",
							},
						},
						{
							Name: "targetErrors",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/event.ErrorEntry",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"event.LatencyEntry": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "key",
									Type: smd.String,
								},
								{
									Name: "count",
									Type: smd.Integer,
								},
								{
									Name: "avgMs",
									Type: smd.Float,
								},
								{
									Name: "maxMs",
									Type: smd.Float,
								},
								{
									Name: "p95Ms",
									Type: smd.Float,
								},
							},
						},
						"event.ErrorEntry": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "key",
									Type: smd.String,
								},
								{
									Name: "total",
									Type: smd.Integer,
								},
								{
									Name: "errors5xx",
									Type: smd.Integer,
								},
								{
									Name:        "errorRate",
									Description: `Errors5xx / Total * 100`,
									Type:        smd.Float,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s MetricsService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.MetricsService.History:
		var args = struct {
			Minutes *int `json:"minutes"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"minutes"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		//zenrpc:minutes=5 Number of minutes of history (max 30)
		if args.Minutes == nil {
			var v int = 5
			args.Minutes = &v
		}

		resp.Set(s.History(ctx, *args.Minutes))

	case RPC.MetricsService.RPS:
		resp.Set(s.RPS(ctx))

	case RPC.MetricsService.Tops:
		var args = struct {
			N *int `json:"n"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"n"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		//zenrpc:n=10 Number of top entries
		if args.N == nil {
			var v int = 10
			args.N = &v
		}

		resp.Set(s.Tops(ctx, *args.N))

	case RPC.MetricsService.CaptchaRate:
		var args = struct {
			Minutes *int `json:"minutes"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"minutes"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		//zenrpc:minutes=5 Number of minutes of history (max 30)
		if args.Minutes == nil {
			var v int = 5
			args.Minutes = &v
		}

		resp.Set(s.CaptchaRate(ctx, *args.Minutes))

	case RPC.MetricsService.Latencies:
		resp.Set(s.Latencies(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (StatusService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Get": {
				Description: `Get returns the current service status.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `StatusResponse`,
					Type:        smd.Object,
					TypeName:    "StatusResponse",
					Properties: smd.PropertyList{
						{
							Name: "service",
							Type: smd.String,
						},
						{
							Name: "targets",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "listen",
							Type: smd.String,
						},
						{
							Name: "uptimeSeconds",
							Type: smd.Integer,
						},
						{
							Name: "wafEnabled",
							Type: smd.Boolean,
						},
						{
							Name: "wafMode",
							Type: smd.String,
						},
						{
							Name: "wafParanoiaLevel",
							Type: smd.Integer,
						},
						{
							Name: "rateLimitEnabled",
							Type: smd.Boolean,
						},
						{
							Name: "rateLimitPerIP",
							Type: smd.String,
						},
						{
							Name: "botVerifyEnabled",
							Type: smd.Boolean,
						},
						{
							Name:     "proxyStatus",
							Optional: true,
							Ref:      "#/definitions/proxy.ProxyStatus",
							Type:     smd.Object,
						},
					},
					Definitions: map[string]smd.Definition{
						"proxy.ProxyStatus": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "targets",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/proxy.TargetStatus",
									},
								},
							},
						},
						"proxy.TargetStatus": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "url",
									Type: smd.String,
								},
								{
									Name:        "state",
									Description: `"closed" | "open" | "half-open" | "n/a"`,
									Type:        smd.String,
								},
							},
						},
					},
				},
			},
			"Rules": {
				Description: `Rules returns the current rate limit rules.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `[]RuleInfo`,
					Type:        smd.Array,
					TypeName:    "[]RuleInfo",
					Items: map[string]string{
						"$ref": "#/definitions/RuleInfo",
					},
					Definitions: map[string]smd.Definition{
						"RuleInfo": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "endpoint",
									Type: smd.String,
								},
								{
									Name: "match",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "limit",
									Type: smd.String,
								},
								{
									Name: "action",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s StatusService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}

	switch method {
	case RPC.StatusService.Get:
		resp.Set(s.Get(ctx))

	case RPC.StatusService.Rules:
		resp.Set(s.Rules(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
